### ISSUE TITLE
Run Multiple icon2-docker on the same machine

### ISSUE THREAD

**Issue by pen-pal** [icon-project/icon2-docker#36]
How do you run multiple icon2 docker nodes on the same machine?
Both the docker share common volumes between each-other

Below is the issue encountered while trying to spin up two icon2 docker on the same machine with common volumes.

![image](https://user-images.githubusercontent.com/61139563/150328920-c743c2be-ade5-4395-a6fd-2e28c71781ea.png)

**Comment by JINWOO-J** [comment]
Data volumes cannot be shared between containers.
Network ports and data volumes and Keystore file for each-other container must be set differently.

Refer to the example below.

docker-compose.yml :
```yaml
version: '3.6'
x-common-var: &common-vars
   SERVICE: "SejongNet"  
   GOLOOP_CONSOLE_LEVEL: "info" 
   IS_AUTOGEN_CERT: "true"
   KEY_STORE_FILENAME: "sejong_key.json"
   KEY_PASSWORD: "test1234"   
   MIG_MAIN_TIMEOUT: 1
   SEEDS: "seed-sejong.solidwallet.io:7100"
   ROLE: 0 # preps = 3, citizen = 0
    
services:
   node1:      
      image: 'iconloop/icon2-node'      
      container_name: "icon2-node-1"
      network_mode: bridge      
      restart: "on-failure"
      environment:
         <<: *common-vars
      ports:
         - '7200:7100'
         - '9200:9000'
      cap_add:
         - SYS_TIME
      volumes:
         - ./data_sejong1:/goloop/data # mount a data volumes
         - ./config_sejong1:/goloop/config # mount a config volumes ,Put your used keystore file here.
         - ./logs_sejong1:/goloop/logs

   node2:
      image: 'iconloop/icon2-node'
      container_name: "icon2-node-2"
      network_mode: bridge
      restart: "on-failure"
      environment:
         <<: *common-vars
      ports:
         - '7300:7100'
         - '9300:9000'
      cap_add:
         - SYS_TIME
      volumes:
         - ./data_sejong2:/goloop/data # mount a data volumes
         - ./config_sejong2:/goloop/config # mount a config volumes ,Put your used keystore file here.
         - ./logs_sejong2:/goloop/logs
```

Test :
```bash
[root@jinwoo-bm-01 ~]# curl localhost:9200/admin/chain
[{"cid":"0x9e1477","nid":"0x53","channel":"icon_dex","state":"started","height":14535,"lastError":""}]

[root@jinwoo-bm-01 ~]# curl localhost:9300/admin/chain
[{"cid":"0x9e1477","nid":"0x53","channel":"icon_dex","state":"started","height":14519,"lastError":""}]

```
