### ISSUE TITLE
"API status code is 403" when trying to setup node on Berlin or Sejong testnets

### ISSUE THREAD

**Issue by FidelVe** [icon-project/icon2-docker#51]
Im trying to setup a node on Berlin or Sejong testnets, my goal is to run a validator node on either of these testnet networks to test being able to run validator related tasks in a testnet environment (i.e create network proposals and vote on these proposals, set bonderlist, etc)

when trying to setup I get the following errors (taken from /logs/booting.log)

```
E|20220927-18:40:58.000444|-|BOOTING.LOG|configure.py:145| API status code is 403. (https://networkinfo.solidwallet.io/node_info/Berlin/default_configure.yml)
I|20220927-18:40:58.000000|-|/etc/cont-init.d| [init_manager] abnormal terminated. shutting down container 
I|20220927-18:43:54.000000|-|/etc/cont-init.d| [init_manager] ICON2 Configuration 
I|20220927-18:43:54.000570|-|BOOTING.LOG|configure.py:106| Download new configuration
E|20220927-18:43:55.000771|-|BOOTING.LOG|configure.py:145| API status code is 403. (https://networkinfo.solidwallet.io/node_info/SeJong/default_configure.yml)
I|20220927-18:43:55.000000|-|/etc/cont-init.d| [init_manager] abnormal terminated. shutting down container 
I|20220927-18:45:30.000000|-|/etc/cont-init.d| [init_manager] ICON2 Configuration 
I|20220927-18:45:31.000372|-|BOOTING.LOG|configure.py:106| Download new configuration
E|20220927-18:45:32.000540|-|BOOTING.LOG|configure.py:145| API status code is 403. (https://networkinfo.solidwallet.io/node_info/SeJong/default_configure.yml)
I|20220927-18:45:32.000000|-|/etc/cont-init.d| [init_manager] abnormal terminated. shutting down container
```

This is my docker-compose.yml file:
```
version: "3"
services:
   prep:
     image: iconloop/icon2-node
       #image: iconloop/icon2-node:v1.1.3
     container_name: "icon2-node"
     network_mode: host
        #privileged: true
     restart: "on-failure"
     environment:
        #NTP_SERVER:  time.apple.com
        #GOLOOP_ENGINE: "java"
         SERVICE: "SeJong"  # MainNet, SeJong
         GOLOOP_LOG_LEVEL: "debug" # trace, debug, info, warn, error, fatal, panic
         KEY_STORE_FILENAME: "keystore.json" # e.g. keystore.json read a config/keystore.json
         # e.g. "/goloop/config/keystore.json" read a "config/keystore.json" of host machine
         KEY_PASSWORD: "REDACTED"
         FASTEST_START: "true"    # It can be restored from latest Snapshot DB.
         ROLE: 0 # preps = 3, citizen = 0
         #MAIN_TIME_OUT: 60   # for slow IO issue
         #dns:
           #- "8.8.8.8"
     cap_add:
      - SYS_TIME
     volumes:
      - ./data:/goloop/data # mount a data volumes
      - ./config:/goloop/config # mount a config volumes ,Put your used keystore file here.
      - ./logs:/goloop/logs

     ports:
      - 9000:9000
      - 7100:7100

```
