### ISSUE TITLE
unable to run icon testnet node

### ISSUE THREAD

**Issue by riyasng12** [icon-project/icon2-docker#59]
Hi! I've been trying to run the berlinnet testnet node for ICON. However, after all the required files have been downloaded, I seem to be encountering this error: `s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening`.

The container stops after this.

Here is the screenshot attached for reference:
![image](https://github.com/icon-project/icon2-docker/assets/74088025/04a2e613-236e-4a61-92d6-3276c3aeca0a)

Here is the docker-compose file I am using:
```
version: "3.6"
services:
   prep:
      image: iconloop/icon2-node
      container_name: "icon2-node"
      network_mode: host
      restart: "on-failure"
      environment:
         SERVICE: "BerlinNet"
         GOLOOP_LOG_LEVEL: "debug" 
         KEY_STORE_FILENAME: "keystore.json" 
         KEY_PASSWORD: "gochain"
         FASTEST_START: "true"

         ROLE: 3 # Validator = 3, API Endpoint = 0

      cap_add:
         - SYS_TIME

      volumes:
         - /media/riya/New Volume/data:/goloop/data # mount a data volumes
         - /media/riya/New Volume/config:/goloop/config # mount a config volumes ,Put your used keystore file here.
         - /media/riya/New Volume/logs:/goloop/logs
      ports:
         - 9000:9000
         - 7100:7100
```
